# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjercitoDeLasMurallas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('distrito', models.CharField(max_length=35)),
                ('muralla', models.CharField(choices=[('Muralla Maria', 'Muralla Maria'), ('Muralla Sina', 'Muralla Sina'), ('Muralla Rose', 'Muralla Rose')], max_length=13)),
                ('ejercito', models.CharField(choices=[('Tropas Estacionarias', 'Tropas Estacionarias'), ('Legion de Reconocimiento', 'Legion de Reconocimiento'), ('Policia Militar', 'Policia Militar')], max_length=24)),
                ('gigantesAsesinados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuerrerosZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('raza', models.CharField(max_length=20)),
                ('nivelKi', models.FloatField()),
                ('transformacionMasPoderosa', models.CharField(max_length=30, null=True)),
                ('habilidadEspecial', models.CharField(max_length=30)),
                ('planetaOrigen', models.CharField(max_length=20)),
                ('universo', models.CharField(choices=[('9', '9'), ('5', '5'), ('8', '8'), ('6', '6'), ('12', '12'), ('4', '4'), ('7', '7'), ('3', '3'), ('10', '10'), ('11', '11'), ('2', '2'), ('1', '1')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Musicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('edad', models.IntegerField()),
                ('instrumento', models.CharField(choices=[('Violin', 'Violin'), ('Piano', 'Piano')], max_length=6)),
                ('concursosGanados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ninjas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('clan', models.CharField(max_length=35)),
                ('aldea', models.CharField(max_length=35)),
                ('nivelMilitar', models.CharField(choices=[('Jonin', 'Jonin'), ('Sannin', 'Sannin'), ('Anbu', 'Anbu'), ('Genin', 'Genin'), ('Kage', 'Kage'), ('Chunin', 'Chunin')], max_length=6)),
                ('jutsu', models.CharField(max_length=50)),
                ('nivelChakra', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Practicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practica', models.IntegerField()),
                ('nombre', models.CharField(max_length=75)),
                ('realizado', models.BooleanField(default=False)),
            ],
        ),
    ]
