# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0002_auto_20171019_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('Ecolares', 'Ecolares'), ('Historico', 'Historico'), ('Infantil', 'Infantil'), ('Demonios', 'Demonios'), ('Fantasía', 'Fantasía'), ('Música', 'Música'), ('Psicológico', 'Psicológico'), ('Recuentros de la vida', 'Recuentros de la vida'), ('Ecchi', 'Ecchi'), ('Jegos', 'Jegos'), ('Carreras', 'Carreras'), ('Romance', 'Romance'), ('Sobrenatural', 'Sobrenatural'), ('Espacial', 'Espacial'), ('Drama', 'Drama'), ('Josei', 'Josei'), ('Shoujo', 'Shoujo'), ('Demencia', 'Demencia'), ('Yuri', 'Yuri'), ('Harem', 'Harem'), ('Yaoi', 'Yaoi'), ('Militar', 'Militar'), ('Suspenso', 'Suspenso'), ('Acción', 'Acción'), ('Deportes', 'Deportes'), ('Parodia', 'Parodia'), ('Superpoeders', 'Superpoeders'), ('Vampiros', 'Vampiros'), ('Aventuras', 'Aventuras'), ('Magia', 'Magia'), ('Comedia', 'Comedia'), ('Samurai', 'Samurai'), ('Seinen', 'Seinen'), ('Shounen', 'Shounen'), ('Terror', 'Terror'), ('Artes Marciales', 'Artes Marciales'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Mecha', 'Mecha'), ('Misterio', 'Misterio'), ('Policía', 'Policía')], max_length=21)),
                ('episodios', models.IntegerField()),
                ('añoLanzamiento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ejercitodelasmurallas',
            name='ejercito',
            field=models.CharField(choices=[('Tropas Estacionarias', 'Tropas Estacionarias'), ('Legion de Reconocimiento', 'Legion de Reconocimiento'), ('Policia Militar', 'Policia Militar')], max_length=24),
        ),
        migrations.AlterField(
            model_name='ejercitodelasmurallas',
            name='muralla',
            field=models.CharField(choices=[('Muralla Sina', 'Muralla Sina'), ('Muralla Rose', 'Muralla Rose'), ('Muralla Maria', 'Muralla Maria')], max_length=13),
        ),
        migrations.AlterField(
            model_name='guerrerosz',
            name='universo',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('3', '3'), ('6', '6'), ('8', '8'), ('11', '11'), ('1', '1'), ('9', '9'), ('2', '2'), ('12', '12'), ('10', '10'), ('7', '7')], max_length=2),
        ),
        migrations.AlterField(
            model_name='musicos',
            name='instrumento',
            field=models.CharField(choices=[('Piano', 'Piano'), ('Violin', 'Violin')], max_length=6),
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='nivelMilitar',
            field=models.CharField(choices=[('Chunin', 'Chunin'), ('Anbu', 'Anbu'), ('Genin', 'Genin'), ('Sannin', 'Sannin'), ('Jonin', 'Jonin'), ('Kage', 'Kage')], max_length=6),
        ),
    ]
