# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0003_auto_20171114_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='genero',
            field=models.CharField(choices=[('Jegos', 'Jegos'), ('Artes Marciales', 'Artes Marciales'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Ecolares', 'Ecolares'), ('Espacial', 'Espacial'), ('Superpoeders', 'Superpoeders'), ('Carreras', 'Carreras'), ('Magia', 'Magia'), ('Suspenso', 'Suspenso'), ('Harem', 'Harem'), ('Infantil', 'Infantil'), ('Yuri', 'Yuri'), ('Shoujo', 'Shoujo'), ('Policía', 'Policía'), ('Militar', 'Militar'), ('Parodia', 'Parodia'), ('Romance', 'Romance'), ('Sobrenatural', 'Sobrenatural'), ('Terror', 'Terror'), ('Vampiros', 'Vampiros'), ('Ecchi', 'Ecchi'), ('Historico', 'Historico'), ('Aventuras', 'Aventuras'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Mecha', 'Mecha'), ('Recuentros de la vida', 'Recuentros de la vida'), ('Música', 'Música'), ('Samurai', 'Samurai'), ('Demonios', 'Demonios'), ('Misterio', 'Misterio'), ('Psicológico', 'Psicológico'), ('Seinen', 'Seinen'), ('Shounen', 'Shounen'), ('Deportes', 'Deportes'), ('Josei', 'Josei'), ('Acción', 'Acción'), ('Yaoi', 'Yaoi'), ('Demencia', 'Demencia')], max_length=21),
        ),
        migrations.AlterField(
            model_name='ejercitodelasmurallas',
            name='ejercito',
            field=models.CharField(choices=[('Tropas Estacionarias', 'Tropas Estacionarias'), ('Policia Militar', 'Policia Militar'), ('Legion de Reconocimiento', 'Legion de Reconocimiento')], max_length=24),
        ),
        migrations.AlterField(
            model_name='guerrerosz',
            name='universo',
            field=models.CharField(choices=[('2', '2'), ('6', '6'), ('1', '1'), ('7', '7'), ('12', '12'), ('3', '3'), ('8', '8'), ('4', '4'), ('10', '10'), ('11', '11'), ('9', '9'), ('5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='musicos',
            name='instrumento',
            field=models.CharField(choices=[('Violin', 'Violin'), ('Piano', 'Piano')], max_length=6),
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='nivelMilitar',
            field=models.CharField(choices=[('Chunin', 'Chunin'), ('Jonin', 'Jonin'), ('Anbu', 'Anbu'), ('Genin', 'Genin'), ('Kage', 'Kage'), ('Sannin', 'Sannin')], max_length=6),
        ),
    ]
