# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('p', '0005_auto_20171121_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='animes',
            name='genero',
            field=models.CharField(choices=[('Yuri', 'Yuri'), ('Harem', 'Harem'), ('Carreras', 'Carreras'), ('Comedia', 'Comedia'), ('Demonios', 'Demonios'), ('Mecha', 'Mecha'), ('Militar', 'Militar'), ('Misterio', 'Misterio'), ('Deportes', 'Deportes'), ('Historico', 'Historico'), ('Demencia', 'Demencia'), ('Josei', 'Josei'), ('Música', 'Música'), ('Samurai', 'Samurai'), ('Seinen', 'Seinen'), ('Superpoeders', 'Superpoeders'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Espacial', 'Espacial'), ('Infantil', 'Infantil'), ('Vampiros', 'Vampiros'), ('Acción', 'Acción'), ('Fantasía', 'Fantasía'), ('Aventuras', 'Aventuras'), ('Ecchi', 'Ecchi'), ('Shoujo', 'Shoujo'), ('Sobrenatural', 'Sobrenatural'), ('Parodia', 'Parodia'), ('Artes Marciales', 'Artes Marciales'), ('Drama', 'Drama'), ('Recuentros de la vida', 'Recuentros de la vida'), ('Shounen', 'Shounen'), ('Suspenso', 'Suspenso'), ('Romance', 'Romance'), ('Terror', 'Terror'), ('Magia', 'Magia'), ('Policía', 'Policía'), ('Yaoi', 'Yaoi'), ('Psicológico', 'Psicológico'), ('Jegos', 'Jegos'), ('Ecolares', 'Ecolares')], max_length=21),
        ),
        migrations.AlterField(
            model_name='ejercitodelasmurallas',
            name='ejercito',
            field=models.CharField(choices=[('Legion de Reconocimiento', 'Legion de Reconocimiento'), ('Policia Militar', 'Policia Militar'), ('Tropas Estacionarias', 'Tropas Estacionarias')], max_length=24),
        ),
        migrations.AlterField(
            model_name='ejercitodelasmurallas',
            name='muralla',
            field=models.CharField(choices=[('Muralla Rose', 'Muralla Rose'), ('Muralla Sina', 'Muralla Sina'), ('Muralla Maria', 'Muralla Maria')], max_length=13),
        ),
        migrations.AlterField(
            model_name='guerrerosz',
            name='universo',
            field=models.CharField(choices=[('1', '1'), ('4', '4'), ('9', '9'), ('12', '12'), ('5', '5'), ('2', '2'), ('11', '11'), ('6', '6'), ('8', '8'), ('3', '3'), ('10', '10'), ('7', '7')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='nivelMilitar',
            field=models.CharField(choices=[('Kage', 'Kage'), ('Jonin', 'Jonin'), ('Genin', 'Genin'), ('Chunin', 'Chunin'), ('Anbu', 'Anbu'), ('Sannin', 'Sannin')], max_length=6),
        ),
    ]
