# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0006_auto_20171128_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='genero',
            field=models.CharField(choices=[('Ciencia Ficción', 'Ciencia Ficción'), ('Comedia', 'Comedia'), ('Ecchi', 'Ecchi'), ('Música', 'Música'), ('Sobrenatural', 'Sobrenatural'), ('Demencia', 'Demencia'), ('Ecolares', 'Ecolares'), ('Carreras', 'Carreras'), ('Espacial', 'Espacial'), ('Fantasía', 'Fantasía'), ('Militar', 'Militar'), ('Josei', 'Josei'), ('Samurai', 'Samurai'), ('Superpoeders', 'Superpoeders'), ('Harem', 'Harem'), ('Policía', 'Policía'), ('Infantil', 'Infantil'), ('Drama', 'Drama'), ('Magia', 'Magia'), ('Acción', 'Acción'), ('Psicológico', 'Psicológico'), ('Yuri', 'Yuri'), ('Deportes', 'Deportes'), ('Seinen', 'Seinen'), ('Shoujo', 'Shoujo'), ('Shounen', 'Shounen'), ('Terror', 'Terror'), ('Suspenso', 'Suspenso'), ('Yaoi', 'Yaoi'), ('Historico', 'Historico'), ('Jegos', 'Jegos'), ('Aventuras', 'Aventuras'), ('Recuentros de la vida', 'Recuentros de la vida'), ('Romance', 'Romance'), ('Vampiros', 'Vampiros'), ('Artes Marciales', 'Artes Marciales'), ('Demonios', 'Demonios'), ('Parodia', 'Parodia'), ('Misterio', 'Misterio'), ('Mecha', 'Mecha')], max_length=21),
        ),
        migrations.AlterField(
            model_name='ejercitodelasmurallas',
            name='ejercito',
            field=models.CharField(choices=[('Tropas Estacionarias', 'Tropas Estacionarias'), ('Policia Militar', 'Policia Militar'), ('Legion de Reconocimiento', 'Legion de Reconocimiento')], max_length=24),
        ),
        migrations.AlterField(
            model_name='guerrerosz',
            name='universo',
            field=models.CharField(choices=[('7', '7'), ('11', '11'), ('1', '1'), ('8', '8'), ('9', '9'), ('12', '12'), ('4', '4'), ('5', '5'), ('2', '2'), ('10', '10'), ('3', '3'), ('6', '6')], max_length=2),
        ),
        migrations.AlterField(
            model_name='musicos',
            name='instrumento',
            field=models.CharField(choices=[('Violin', 'Violin'), ('Piano', 'Piano')], max_length=6),
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='nivelMilitar',
            field=models.CharField(choices=[('Anbu', 'Anbu'), ('Chunin', 'Chunin'), ('Sannin', 'Sannin'), ('Genin', 'Genin'), ('Kage', 'Kage'), ('Jonin', 'Jonin')], max_length=6),
        ),
    ]
