# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0007_auto_20171129_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='genero',
            field=models.CharField(choices=[('Recuentros de la vida', 'Recuentros de la vida'), ('Acción', 'Acción'), ('Artes Marciales', 'Artes Marciales'), ('Carreras', 'Carreras'), ('Misterio', 'Misterio'), ('Música', 'Música'), ('Seinen', 'Seinen'), ('Demonios', 'Demonios'), ('Infantil', 'Infantil'), ('Yuri', 'Yuri'), ('Historico', 'Historico'), ('Romance', 'Romance'), ('Samurai', 'Samurai'), ('Psicológico', 'Psicológico'), ('Ecchi', 'Ecchi'), ('Drama', 'Drama'), ('Mecha', 'Mecha'), ('Yaoi', 'Yaoi'), ('Magia', 'Magia'), ('Jegos', 'Jegos'), ('Harem', 'Harem'), ('Militar', 'Militar'), ('Vampiros', 'Vampiros'), ('Aventuras', 'Aventuras'), ('Policía', 'Policía'), ('Espacial', 'Espacial'), ('Shounen', 'Shounen'), ('Comedia', 'Comedia'), ('Fantasía', 'Fantasía'), ('Ecolares', 'Ecolares'), ('Josei', 'Josei'), ('Parodia', 'Parodia'), ('Sobrenatural', 'Sobrenatural'), ('Deportes', 'Deportes'), ('Shoujo', 'Shoujo'), ('Demencia', 'Demencia'), ('Superpoeders', 'Superpoeders'), ('Terror', 'Terror'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Suspenso', 'Suspenso')], max_length=21),
        ),
        migrations.AlterField(
            model_name='ejercitodelasmurallas',
            name='ejercito',
            field=models.CharField(choices=[('Policia Militar', 'Policia Militar'), ('Legion de Reconocimiento', 'Legion de Reconocimiento'), ('Tropas Estacionarias', 'Tropas Estacionarias')], max_length=24),
        ),
        migrations.AlterField(
            model_name='ejercitodelasmurallas',
            name='muralla',
            field=models.CharField(choices=[('Muralla Sina', 'Muralla Sina'), ('Muralla Maria', 'Muralla Maria'), ('Muralla Rose', 'Muralla Rose')], max_length=13),
        ),
        migrations.AlterField(
            model_name='guerrerosz',
            name='universo',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('5', '5'), ('6', '6'), ('7', '7'), ('10', '10'), ('12', '12'), ('4', '4'), ('9', '9'), ('8', '8'), ('1', '1'), ('11', '11')], max_length=2),
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='nivelMilitar',
            field=models.CharField(choices=[('Kage', 'Kage'), ('Anbu', 'Anbu'), ('Jonin', 'Jonin'), ('Sannin', 'Sannin'), ('Chunin', 'Chunin'), ('Genin', 'Genin')], max_length=6),
        ),
    ]
