# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0008_auto_20171129_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='genero',
            field=models.CharField(choices=[('Jegos', 'Jegos'), ('Romance', 'Romance'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Acción', 'Acción'), ('Comedia', 'Comedia'), ('Demencia', 'Demencia'), ('Ecchi', 'Ecchi'), ('Harem', 'Harem'), ('Mecha', 'Mecha'), ('Música', 'Música'), ('Carreras', 'Carreras'), ('Deportes', 'Deportes'), ('Magia', 'Magia'), ('Militar', 'Militar'), ('Recuentros de la vida', 'Recuentros de la vida'), ('Seinen', 'Seinen'), ('Espacial', 'Espacial'), ('Vampiros', 'Vampiros'), ('Artes Marciales', 'Artes Marciales'), ('Aventuras', 'Aventuras'), ('Terror', 'Terror'), ('Ecolares', 'Ecolares'), ('Psicológico', 'Psicológico'), ('Shoujo', 'Shoujo'), ('Sobrenatural', 'Sobrenatural'), ('Shounen', 'Shounen'), ('Fantasía', 'Fantasía'), ('Policía', 'Policía'), ('Historico', 'Historico'), ('Parodia', 'Parodia'), ('Josei', 'Josei'), ('Drama', 'Drama'), ('Samurai', 'Samurai'), ('Suspenso', 'Suspenso'), ('Infantil', 'Infantil'), ('Superpoeders', 'Superpoeders'), ('Yaoi', 'Yaoi'), ('Yuri', 'Yuri'), ('Demonios', 'Demonios'), ('Misterio', 'Misterio')], max_length=21),
        ),
        migrations.AlterField(
            model_name='ejercitodelasmurallas',
            name='ejercito',
            field=models.CharField(choices=[('Policia Militar', 'Policia Militar'), ('Tropas Estacionarias', 'Tropas Estacionarias'), ('Legion de Reconocimiento', 'Legion de Reconocimiento')], max_length=24),
        ),
        migrations.AlterField(
            model_name='guerrerosz',
            name='universo',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('9', '9'), ('5', '5'), ('1', '1'), ('8', '8'), ('10', '10'), ('2', '2'), ('7', '7'), ('11', '11'), ('12', '12'), ('6', '6')], max_length=2),
        ),
        migrations.AlterField(
            model_name='musicos',
            name='instrumento',
            field=models.CharField(choices=[('Piano', 'Piano'), ('Violin', 'Violin')], max_length=6),
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='nivelMilitar',
            field=models.CharField(choices=[('Genin', 'Genin'), ('Sannin', 'Sannin'), ('Chunin', 'Chunin'), ('Anbu', 'Anbu'), ('Jonin', 'Jonin'), ('Kage', 'Kage')], max_length=6),
        ),
    ]
