# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p', '0009_auto_20171129_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='genero',
            field=models.CharField(choices=[('Policía', 'Policía'), ('Recuentros de la vida', 'Recuentros de la vida'), ('Harem', 'Harem'), ('Carreras', 'Carreras'), ('Demonios', 'Demonios'), ('Vampiros', 'Vampiros'), ('Yaoi', 'Yaoi'), ('Demencia', 'Demencia'), ('Espacial', 'Espacial'), ('Deportes', 'Deportes'), ('Shounen', 'Shounen'), ('Artes Marciales', 'Artes Marciales'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Magia', 'Magia'), ('Misterio', 'Misterio'), ('Suspenso', 'Suspenso'), ('Yuri', 'Yuri'), ('Fantasía', 'Fantasía'), ('Samurai', 'Samurai'), ('Jegos', 'Jegos'), ('Ecolares', 'Ecolares'), ('Infantil', 'Infantil'), ('Psicológico', 'Psicológico'), ('Superpoeders', 'Superpoeders'), ('Acción', 'Acción'), ('Josei', 'Josei'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Música', 'Música'), ('Parodia', 'Parodia'), ('Shoujo', 'Shoujo'), ('Aventuras', 'Aventuras'), ('Sobrenatural', 'Sobrenatural'), ('Historico', 'Historico'), ('Militar', 'Militar'), ('Romance', 'Romance'), ('Terror', 'Terror'), ('Mecha', 'Mecha'), ('Ecchi', 'Ecchi'), ('Seinen', 'Seinen')], max_length=21),
        ),
        migrations.AlterField(
            model_name='ejercitodelasmurallas',
            name='muralla',
            field=models.CharField(choices=[('Muralla Rose', 'Muralla Rose'), ('Muralla Sina', 'Muralla Sina'), ('Muralla Maria', 'Muralla Maria')], max_length=13),
        ),
        migrations.AlterField(
            model_name='guerrerosz',
            name='universo',
            field=models.CharField(choices=[('5', '5'), ('1', '1'), ('2', '2'), ('12', '12'), ('9', '9'), ('4', '4'), ('6', '6'), ('11', '11'), ('8', '8'), ('10', '10'), ('7', '7'), ('3', '3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='musicos',
            name='instrumento',
            field=models.CharField(choices=[('Violin', 'Violin'), ('Piano', 'Piano')], max_length=6),
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='nivelMilitar',
            field=models.CharField(choices=[('Jonin', 'Jonin'), ('Genin', 'Genin'), ('Chunin', 'Chunin'), ('Kage', 'Kage'), ('Anbu', 'Anbu'), ('Sannin', 'Sannin')], max_length=6),
        ),
    ]
